.PHONY: build
build:
	@mkdir -p bin
	@go build -i -v -o ./bin/godl

.PHONY: test
test:
	@go test --race -v -i ./internal/...
	@go test --race -v ./internal/...
	@go vet ./internal/...
	@golint ./internal/...
