.PHONY: build
build:
	@mkdir -p bin
	@go build -i -v -o ./bin/godl

.PHONY: test
test:
	@go test --race -covermode=atomic -v -i ./internal/...
	@go test --race -covermode=atomic -v ./internal/...
	@go vet ./internal/...
	@golint ./internal/...
	@go vet .
	@golint .
